language: php
php:
  - 5.4
branches:
  only:
    - master
    - dev
before_script:
  - wget http://pecl.php.net/get/mongo-1.2.10.tgz
  - tar -xzf mongo-1.2.10.tgz
  - sh -c "cd mongo-1.2.10 && phpize && ./configure --enable-mongo && make && sudo make install"
  - echo "extension=mongo.so" >> `php --ini | grep "Loaded Configuration" | sed -e "s|.*:\s*||"`
  - composer self-update
  - composer install --dev
  - chmod 711 bin/*
  - chmod 777 data/cache/Dibber/Document/Hydrator/ data/cache/Dibber/Document/Proxy/
script: php vendor/mageekguy/atoum/scripts/runner.php -d tests/Dibber/
notifications:
  irc: "irc.freenode.org#dibber"