script: bin/tests.sh
language: php
php:
  - 5.4
before_script:
  - wget http://getcomposer.org/composer.phar
  - php composer.phar install --dev
notifications:
  irc: "irc.freenode.org#dibber"