<?= $this->doctype(); ?>

<html lang="en">
  <head>
    <meta charset="utf-8">
    <?= $this->headTitle('dibber')->setSeparator(' - ')->setAutoEscape(false) ?>

    <?= $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0') ?>

    <!-- Le styles -->
    <?= $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/images/favicon.ico'])
                    ->appendStylesheet($this->assetsPath() . '/css/index.css') ?>

    <!-- Scripts -->
    <?= $this->headScript()->setAllowArbitraryAttributes(true)
                                  ->appendFile($this->assetsPath() . '/js/libs/html5.js', 'text/javascript', ['conditional' => 'lt IE 9'])
                                  ->appendFile($this->assetsPath() . '/js/libs/require.js', 'text/javascript', ['data-main' => '/app/config']) ?>

  </head>

  <body>

    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">

            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="<?= $this->url('dibber') ?>">dibber</a>
          <div class="nav-collapse">
            <ul class="nav">
              <li class="active"><a href="<?= $this->url('dibber') ?>"><?= $this->translate('Home') ?></a></li>
              <li><a href="<?= $this->url('dibber/users') ?>page/1"><?= $this->translate('Users') ?></a></li>
              <li><a href="<?= $this->url('dibber/places') ?>page/1"><?= $this->translate('Places') ?></a></li>
            </ul>
          </div><!--/.nav-collapse -->
          <div id="userbox" class="nav-collapse">
            <ul id="user-links" class="nav">
              <?php if ($this->zfcUserIdentity()) : ?>
              <li><a href="<?= $this->url('dibber/profile') ?>"><?= $this->translate('Profile') ?></a></li>
              <li><a href="<?= $this->url('dibber/logout') ?>"><?= $this->translate('Sign out') ?></a></li>
              <?php else : ?>
              <li><a href="<?= $this->url('dibber/login') ?>"><?= $this->translate('Sign in') ?></a></li>
              <?php endif; ?>
            </ul>
          </div>
        </div>
      </div>
    </div>

    <div class="container">

      <?= $this->content; ?>

      <hr>

      <footer>
        <p>&copy; 2005 - 2012 by Zend Technologies Ltd. <?= $this->translate('All rights reserved.') ?></p>
      </footer>

    </div> <!-- /container -->

  <?= $this->inlineScript() ?>
  </body>
</html>
