<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Dibber\WebService\Module'                              => __DIR__ . '/Module.php',
    'Dibber\WebService\PostProcessor\Image'                 => __DIR__ . '/src/WebService/PostProcessor/Image.php',
    'Dibber\WebService\PostProcessor\AbstractPostProcessor' => __DIR__ . '/src/WebService/PostProcessor/AbstractPostProcessor.php',
    'Dibber\WebService\PostProcessor\Json'                  => __DIR__ . '/src/WebService/PostProcessor/Json.php',
    'Dibber\WebService\Controller\UserController'           => __DIR__ . '/src/WebService/Controller/UserController.php',
    'Dibber\WebService\Controller\PlaceController'          => __DIR__ . '/src/WebService/Controller/PlaceController.php',
    'Dibber\WebService\Controller\BaseController'           => __DIR__ . '/src/WebService/Controller/BaseController.php',
);