<div style="float:left; padding-right:16px; width: 150px;">
    <h2><?= $place->getName() ?></h2>
</div>
<div style="margin-left: 160px;">
    <?php if ($place->getUsers()) : ?>
    <div id="users">
        <h3>Its members</h3>
        <ul class="nav nav-tabs nav-stacked">
        <?php foreach ($place->getUsers() as $user) : ?>
            <li><a href="<?= $this->url('dibber') . $user->getLogin()?>" data-bypass><?= $this->zfcUserDisplayName($user) ?></a></li>
        <?php endforeach; ?>
        </ul>
    <?php endif; ?>
    </div>
</div>
<div style="clear:both;"></div>
