<div style="float:left; padding-right:16px; width: 150px;">
    <h3>The places</h3>
</div>
<div style="margin-left: 160px;">
<?php if (count($places)) : ?>
    <ul class="nav nav-tabs nav-stacked">
        <?php foreach ($places as $place) : ?>
            <li><a href="<?php echo $this->url('dibber') . $place->getLogin()?>"><?php echo $place->getName() ?></a></li>
        <?php endforeach; ?>
    </ul>
<?php endif; ?>
</div>
<div style="clear:both;"></div>
