<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Dibber\Tests\Units\Document\Zone'        => __DIR__ . '/Tests/Units/Document/Zone.php',
    'Dibber\Tests\Units\Document\Thing'       => __DIR__ . '/Tests/Units/Document/Thing.php',
    'Dibber\Tests\Units\Document\User'        => __DIR__ . '/Tests/Units/Document/User.php',
    'Dibber\Tests\Units\Document\Place'       => __DIR__ . '/Tests/Units/Document/Place.php',
    'Dibber\Tests\Units\Document\Test'        => __DIR__ . '/Tests/Units/Document/Test.php',
    'Dibber\Tests\Units\Document\Field'       => __DIR__ . '/Tests/Units/Document/Field.php',
    'Dibber\Tests\Units\Document\Mapper\Base' => __DIR__ . '/Tests/Units/Document/Mapper/Base.php',
    'Dibber\Tests\Units\Document\Mapper\User' => __DIR__ . '/Tests/Units/Document/Mapper/User.php',
    'Dibber\Tests\Units\Document\Mapper\Test' => __DIR__ . '/Tests/Units/Document/Mapper/Test.php',
    'Dibber\Tests\Units\Test'                 => __DIR__ . '/Tests/Units/Test.php',
);