<div style="float:left; padding-right:16px; width: 150px;">
    <h2><?= $this->zfcUserDisplayName($user) ?></h2>
    <?= $this->gravatar($user->getEmail(), ['img_size' => 150]) ?>
</div>
<div style="margin-left: 160px;">
    <?php if ($user->getPlaces()) : ?>
    <div id="places">
        <h3>Its places</h3>
        <ul class="nav nav-tabs nav-stacked">
        <?php foreach ($user->getPlaces() as $place) : ?>
            <li><a href="<?= $this->url('dibber') . $place->getLogin()?>" data-bypass><?= $place->getName() ?></a></li>
        <?php endforeach; ?>
        </ul>
    <?php endif; ?>
    </div>
</div>
<div style="clear:both;"></div>
