<div style="float:left; padding-right:16px; width: 150px;">
    <h3>The users</h3>
</div>
<div style="margin-left: 160px;">
<?php if (count($users)) : ?>
    <ul class="nav nav-tabs nav-stacked">
        <?php foreach ($users as $user) : ?>
            <li><a href="<?= $this->url('dibber') . $user->getLogin()?>"><?= $this->zfcUserDisplayName($user) ?></a></li>
        <?php endforeach; ?>
    </ul>
<?php endif; ?>
</div>
<div style="clear:both;"></div>
