<div style="float:left; padding-right:16px; width: 150px;">
    <h3>The users</h3>
</div>
<div style="margin-left: 160px;">
<?php if (count($users)) : ?>
    <ul class="nav nav-tabs nav-stacked">
        <?php foreach ($users as $user) : ?>
            <?php if ($user instanceof \Dibber\Document\User) : ?>
                <li><a href="<?php echo $this->url('dibber') . $user->getLogin()?>"><?php echo $this->zfcUserDisplayName($user) ?></a></li>
            <?php endif; ?>
        <?php endforeach; ?>
    </ul>
<?php endif; ?>
</div>
<div style="clear:both;"></div>
